name: Cleanup packages

on:
  workflow_dispatch:
  schedule:
    - cron: '34 8 * * sun'

permissions:
  contents: read
  packages: write

jobs:
  cleanup-packages:
    runs-on: ubuntu-latest

    name: Cleanup ${{ matrix.package }}

    strategy:
      matrix:
        package:
          - vana-logistiek-frontend
          - vana-logistiek-docs
          - vana-logistiek-backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: 'false'

      - name: Delete old versions of ${{ matrix.package }}
        uses: smartsquaregmbh/delete-old-packages@v0.8.1
        with:
          user: roelofr
          type: container
          keep: 5
          names: ${{ matrix.package }}

      - name: Delete orphan and untagged versions of ${{ matrix.package }}
        run: .github/prune-package.sh roelofr ${{ matrix.package }}
        env:
          GH_TOKEN: ${{ github.token }}
