name: Cleanup packages

on:
  workflow_dispatch:
  schedule:
    - cron: '34 8 * * sun'

permissions:
  contents: read
  packages: write

jobs:
  cleanup-packages:
    runs-on: ubuntu-latest

    name: Cleanup ${{ matrix.package }}

    strategy:
      matrix:
        package:
          - vana-logistiek-frontend
          - vana-logistiek-docs
          - vana-logistiek-backend

    steps:
      - uses: actions/delete-package-versions@v5
        with:
          owner: ${{ github.repository_owner }}
          package-name: ${{ matrix.package }}
          package-type: container
          min-versions-to-keep: 5

      - uses: actions/delete-package-versions@v5
        with:
          owner: ${{ github.repository_owner }}
          package-name: ${{ matrix.package }}
          package-type: container
          delete-only-untagged-versions: true
          min-versions-to-keep: 0
