name: Cleanup packages

on:
  workflow_dispatch:
  registry_package:
    types:
      - published

permissions:
  packages: write

jobs:
  cleanup-packages:
    runs-on: ubuntu-latest

    steps:
      - uses: smartsquaregmbh/delete-old-packages@v0.8.1
        with:
          user: roelofr
          type: container
          keep: 5
          names: |
            vana-logistiek-frontend
            vana-logistiek-backend
